### ISSUE TITLE
Make Username Case Insensitive

### ISSUE THREAD

**Issue by Daadan** [directedmachines/customer-support#1]
username for https://directedmachines.com/dashboard/ui/ is case sensitive - annoying.

Please make case insensitive.

**Comment by georgechrysanthakopoulos** [comment]
will do, will resolve this issue once commit is pushed

**Comment by georgechrysanthakopoulos** [comment]
all lower case email is now supported for your account, verified.

**Comment by KatTeo** [comment]
[ePTO_1.PDF](https://github.com/directedmachines/customer-support/files/5767188/ePTO_1.PDF)
[ePTO_2.PDF](https://github.com/directedmachines/customer-support/files/5767189/ePTO_2.PDF)
