### ISSUE TITLE
Mower not coming up to full power

### ISSUE THREAD

**Issue by abtinling** [directedmachines/customer-support#10]
In manual mode, the mower only comes on at low power. Adjusting the power level and toggling the PTO in the UI don't have an affect. When in the autonomous mode, the mower *does* come up to the power level set in the Plan. (This occurred after a reset via the webUI to reacquire a cellular data connection).

**Comment by georgechrysanthakopoulos** [comment]
I tested this year with a new LCR about to ship out, and in manual mode it is coming up to full power. To narrow this further can you please try this again, and note the time, to closest second? then post a comment here with the time and PTO/AUX power expected and I can check telemetry.

**Comment by georgechrysanthakopoulos** [comment]
there was a brief regression of the weekend due to some configuration file renames, it appears resolved now, once robot connected and OTA kicked in
