### ISSUE TITLE
Mower items easily bent

### ISSUE THREAD

**Issue by abtinling** [directedmachines/customer-support#12]
Admittedly, my experience with a brush mower and a previous tractor may have set unrealistic expectations, but there are a couple areas on the mower that bend easily when hidden obstacles or ground level variations are encountered. I'll definitely run the mower on the back when pushing through brush now, but figured you'd like to see what happens. I was able to straighten the pieces with a vice and a handheld sledgehammer, so I'm not blocked. The other thing to note, is that the hitch pin clips for the ground following wheels easily get snagged and lost in brush (I've had this issue on my old tractor, too).

![image](https://user-images.githubusercontent.com/84051775/124800433-7c1eea80-df0a-11eb-8506-ddf8f27fcf7e.png)
![image](https://user-images.githubusercontent.com/84051775/124800498-90fb7e00-df0a-11eb-8ca8-386259b17204.png)

**Comment by georgechrysanthakopoulos** [comment]
Thanks @abtinling, good feedback. We decided to give you a ground follow mower (which has the casters attached to deck and can be used resting on ground) even if you had specified brush clearing as the primary application. The risk was exactly what you encountered :) Basically, if you want to do brush clearing, either go robot casters first, or, remove the mowing deck casters. This is expected in heavy brush use. I would be happy to give you free replacements for any part that is bent out of shape and no longer functional, please email support @ directed machines .com when you need replacement parts. Free of charge in the first year!
