### ISSUE TITLE
Mower cover accumulating clippings

### ISSUE THREAD

**Issue by abtinling** [directedmachines/customer-support#13]
After mowing tall grass and dandelions, the area under the mower drive cover got very full of clippings. Wondering if adding some longer bolts and spacers to create a larger gap between the cover and the deck might help with self-clearing, or more easily blowing the clippings out with a compressor or leaf blower. Maybe a centrifugal fan mechanism incorporated into the drive would eject the clippings? Also wondering if the clippings are being drawn up from below, as the holes for the drive shafts are quite large.

![image](https://user-images.githubusercontent.com/84051775/124801763-0e73be00-df0c-11eb-9699-0ce3b7ace2c9.png)

**Comment by georgechrysanthakopoulos** [comment]
wow, good find, thanks! The cover is new so it looks like we need some design tweaks. I will open an internal mechanical design issue to address this

**Comment by georgechrysanthakopoulos** [comment]
@abtinling our Rev6 mowing deck will eliminate most of the space between the pulley spindles and deck, so clippings will not be able to get "above" into the cover volume. Thanks again for the issue and with helping us improve the mower.
