### ISSUE TITLE
3pt hitch sag

### ISSUE THREAD

**Issue by abtinling** [directedmachines/customer-support#14]
The offset of the linear drive makes the top plate on the hitch susceptible to sag. (Yeah, this might have been exacerbated by a low-speed encounter with an obstacle).

![image](https://user-images.githubusercontent.com/84051775/124802376-c0ab8580-df0c-11eb-9aaf-6d10117a339b.png)

**Comment by georgechrysanthakopoulos** [comment]
on a new robot, with just a mower, the hitch is balanced, here are some pictures on when it was delivered and build:
https://photos.app.goo.gl/3qfC2qGThhbBRMwS8

So it must have gotten bent. I would be happy to help you fix it, or for cost give you a replacement top lift bend ( i think it is 60$).

Customers lifting heavy stuff use dual actuators, one under each side, so it stays balanced.
