### ISSUE TITLE
E-Stop brackets easily dislocated

### ISSUE THREAD

**Issue by abtinling** [directedmachines/customer-support#16]
We have had the brackets regularly vibrate loose, and they are easily knocked of by blackberry canes when pushing through brush. Have since secured with hot melt glue, with the intention of being able to remove in the future if necessary, but hold is good so far.

![image](https://user-images.githubusercontent.com/84051775/126236997-7ca1bb4f-58e7-4fd4-9552-fae428ca20b4.png)

**Comment by georgechrysanthakopoulos** [comment]
Thanks Aaron. Re-design in progress, when ready, we will send you updated STL files to print (or, you can stop by factory to grab one)

**Comment by georgechrysanthakopoulos** [comment]
https://photos.app.goo.gl/D448XJ2EcPWFx8iT8

we have replaced the e-stop 3d prints. @abtinling please let me know on email if you would like us to mail you new metal e-stop mounts. We also have new 3D prints for cameras, which also take on a new 3-in-1 antenna puck. We will also send those to you if you wish, one new antennas are in
