### ISSUE TITLE
Mower deck lower arm bushing out of place

### ISSUE THREAD

**Issue by abtinling** [directedmachines/customer-support#18]
One of the press-fit bushings in the lower arm of the mower deck has come out of place. I have since added quick pins on both sides so that the bushings won't be lost.

![image](https://user-images.githubusercontent.com/84051775/126237960-400641fa-4713-45d0-b4a1-8da53b629128.png)

**Comment by georgechrysanthakopoulos** [comment]
Thanks Aaron, we have changed the linkages ( i know, things move fast ...) to no longer require the inserts (the new ID is a bit oversized, and we use thicker linkage plate) and if properly connected to middle "connector" bar, the linkages can not come off, even if no pins are present on stub shaft.
