### ISSUE TITLE
Mower Power Short

### ISSUE THREAD

**Issue by abtinling** [directedmachines/customer-support#20]
While mowing brush, the mower deck was pushed upwards and the positive power lug on the motor touched the linear drive height adjuster. I noticed it arcing and stopped the mower and turned off the drive power switch. Manually pushed the deck away to make sure there was no more contact. Turned power back on, but now showing a drive enumeration fault. Is there a fuse or circuit breaker I need to replace or reset?
![image](https://user-images.githubusercontent.com/84051775/132144090-24573266-b6b7-4c85-8ef1-1032af88c154.png)

**Comment by georgechrysanthakopoulos** [comment]
@abtinling thanks for the report.
Please follow these instructions to reset the enumeration fault:

https://github.com/directedmachines/customer-support/wiki/LCR-Technical-Bulletins

https://github.com/directedmachines/customer-support/files/7110722/DM-HighCurrentPowerCycle.pdf

i will also contact you over email

**Comment by zackwoodruff** [comment]
Field repair completed, added plastic covers on motor leads to avoid shorts in the future.
