### ISSUE TITLE
Real Sense Camera fogging

### ISSUE THREAD

**Issue by abtinling** [directedmachines/customer-support#22]
One of the depth cameras has water droplets behind the glass causing false positive object avoidance. Have removed to see if warming it will drive off the water.

![image](https://user-images.githubusercontent.com/84051775/139513920-3cafc2f6-c6b0-428f-8d73-33fa28d5c4a1.png)

**Comment by georgechrysanthakopoulos** [comment]
I am glad we have moved on to metal mounts, with better protections.
@abtinling let us know if the camera does not dry or has issue and we will send you a replacement

**Comment by georgechrysanthakopoulos** [comment]
@abtinling reports that camera seems dry and operational after brought indoors and dried
