### ISSUE TITLE
Short run-time before low power state

### ISSUE THREAD

**Issue by abtinling** [directedmachines/customer-support#23]
Have had Percy on the charger for the last few days, but got less than an hour of run-time (mowing) before low power state kicked in while testing a small work area today.

**Comment by georgechrysanthakopoulos** [comment]
Hi Aaron, Percy has not been charging going back the last 24 hours, except for a brief 45 minutes today. You can see it in your telemetry (type 12V in the query box, select 24 hours, you will see batteries at 12.2V).
Not sure why it was only charging for that brief interval, can you please check the cable, charger display?

11:45AM to 12:37AM was AC charging, idle before and after.

<img width="1031" alt="Screen Shot 2021-10-29 at 8 02 08 PM" src="https://user-images.githubusercontent.com/978440/139518140-08d65f27-afc1-40fe-8f87-70f877a571ab.png">

<img width="1366" alt="Screen Shot 2021-10-29 at 8 02 37 PM" src="https://user-images.githubusercontent.com/978440/139518137-9dfcd073-37ab-4fc6-a6b6-9e6897c1847e.png">
<img width="584" alt="Screen Shot 2021-10-29 at 8 04 45 PM" src="https://user-images.githubusercontent.com/978440/139518171-ae34cb03-7291-42d2-aae3-8cd5b943dd0a.png">

**Comment by abtinling** [comment]
Ok, curious, I had Percy plugged in since getting to low power state yesterday. I disconnected the charger this morning and it appeared to kick back on, but only briefly. And the display on the charger seems to have failed, so I'm just going off hearing the fan and seeing the right hand LED go green. After a brief period, both LEDs turned red and the fan went off, with the charge level in the web UI still indicating 67%. In the meantime I've taken advantage of the sun to get a little more charging in today. 
![image](https://user-images.githubusercontent.com/84051775/139561241-3b2d64c5-987c-46b6-852b-b011755a523f.png)

**Comment by georgechrysanthakopoulos** [comment]
@abtinling thanks for confirming (i also just sent you mail about this). Your charger is broken :( This is the third charger that has failed this year. We will replace it free of charge. Let's coordinate over email: if you are in Seattle we can give you a new charger + new camera

**Comment by abtinling** [comment]
Replacement charger was easier to swap than I even expected! Seems to be charging as expected now.
