### ISSUE TITLE
Drive belt for mower

### ISSUE THREAD

**Issue by abtinling** [directedmachines/customer-support#25]
Due to wear, I need to replace the drive belt on Percy's 48 inch mower. I haven't been able to find belt size info on the wiki, so querying here :-) Thanks!

**Comment by okedar** [comment]
Hi, thanks for letting us know. I've added the belt specs to the Wiki linked below. let me know if you have any follow up questions
https://github.com/directedmachines/customer-support/wiki/LCR-48in-electric-mowing-deck-guide#belt-specs
