### ISSUE TITLE
Castor Replacement?

### ISSUE THREAD

**Issue by johnsciarabba** [directedmachines/customer-support#26]
What are the replacement specs for the front castors? Couldn't find in wiki. One of Billy's front castors is bent at top pin that attaches to frame w/ linch pin. I removed it and straighten it but it's still causing that wheel to drag. Going to need to replace.

**Comment by georgechrysanthakopoulos** [comment]
@johnsciarabba please post some images to this issue and we can prepare a shipment / send you cost estimate

**Comment by johnsciarabba** [comment]
The top pin is the only damaged part but I see its welded to the castor frame.

![IMG_6302](https://github.com/directedmachines/customer-support/assets/116497441/883a469e-9688-462d-8c84-bc31bf1fbc85)
![IMG_6303](https://github.com/directedmachines/customer-support/assets/116497441/70f801b2-1698-4b22-b4ea-974d7c64d6e2)
