### ISSUE TITLE
tutorial revisions

### ISSUE THREAD

**Issue by sophia-chrys** [directedmachines/customer-support#6]
TOC generation added to first use guide. instructions:
https://gist.githubusercontent.com/jonschlinkert/ac5d8122bfaaa394f896/raw/bd1106691cf344e972f575c49ba3cf281beeb9b3/markdown-toc_repeated-headings.md

**Comment by sophia-chrys** [comment]
![HitchLiftBend2](https://user-images.githubusercontent.com/77651840/106416002-4f1f5680-6405-11eb-9639-e4c1788d8636.png)
![image (1)](https://user-images.githubusercontent.com/77651840/106416057-6d855200-6405-11eb-9f16-414a4874aca9.png)

**Comment by georgechrysanthakopoulos** [comment]
![IMG_4292](https://user-images.githubusercontent.com/978440/106488555-aefb1900-6468-11eb-8cea-ca75296b34e8.jpg)

**Comment by georgechrysanthakopoulos** [comment]
![Screen Shot 2021-02-03 at 8 17 47 PM](https://user-images.githubusercontent.com/978440/106844261-eaf6cf80-665c-11eb-91c4-2fbc7062690d.png)

**Comment by georgechrysanthakopoulos** [comment]
![Screen Shot 2021-02-04 at 11 04 37 AM](https://user-images.githubusercontent.com/978440/106942615-3fd82b80-66d9-11eb-90c8-6fc0cad346e5.png)
![Screen Shot 2021-02-04 at 11 04 21 AM](https://user-images.githubusercontent.com/978440/106942633-436bb280-66d9-11eb-8ee9-9f92be888e80.png)
![Screen Shot 2021-02-04 at 11 04 01 AM](https://user-images.githubusercontent.com/978440/106942637-449cdf80-66d9-11eb-9b06-371499439a8b.png)

**Comment by sophia-chrys** [comment]
<img width="232" alt="Screen Shot 2021-02-07 at 11 18 40 AM" src="https://user-images.githubusercontent.com/77651840/107157133-4532b180-6937-11eb-8b17-e8efe675f427.png">

**Comment by sophia-chrys** [comment]
<img width="346" alt="Screen Shot 2021-02-07 at 11 20 14 AM" src="https://user-images.githubusercontent.com/77651840/107157253-f0436b00-6937-11eb-9820-4c2de0228173.png">

<img width="170" alt="Screen Shot 2021-02-07 at 11 21 58 AM" src="https://user-images.githubusercontent.com/77651840/107157261-f9343c80-6937-11eb-8b98-3512d22443e1.png">

**Comment by sophia-chrys** [comment]
<img width="503" alt="Screen Shot 2021-02-07 at 11 35 33 AM" src="https://user-images.githubusercontent.com/77651840/107157382-b45cd580-6938-11eb-9c0f-dbd69bbcdb51.png">

**Comment by sophia-chrys** [comment]
![Uploading Screen Shot 2021-02-07 at 12.00.35 PM.png…]()

**Comment by sophia-chrys** [comment]
<img width="504" alt="Screen Shot 2021-02-07 at 12 00 35 PM" src="https://user-images.githubusercontent.com/77651840/107158019-3c90aa00-693c-11eb-99f7-3e4d6db16e72.png">

**Comment by georgechrysanthakopoulos** [comment]
![Screen Shot 2021-02-13 at 11 38 36 PM](https://user-images.githubusercontent.com/978440/107871277-e3050f80-6e54-11eb-83de-649d0746dec0.jpg)

**Comment by georgechrysanthakopoulos** [comment]
<img width="404" alt="Screen Shot 2021-08-07 at 8 10 02 PM" src="https://user-images.githubusercontent.com/978440/128619455-1781149b-2e91-44c9-ba4d-20b3ab3bf5a3.png">

**Comment by georgechrysanthakopoulos** [comment]
<img width="802" alt="Screen Shot 2021-08-07 at 8 14 05 PM" src="https://user-images.githubusercontent.com/978440/128619527-e3024b6d-e46d-4cde-b074-3138a67517f0.png">

**Comment by kdulzo** [comment]
Okay so it’s a plan level setting, not something set per work area or waypoint transit path.

**Comment by georgechrysanthakopoulos** [comment]
![Screen Shot 2021-08-11 at 5 43 18 PM](https://user-images.githubusercontent.com/978440/129121785-f01bca08-cb7f-487b-98c6-2e56d54e4a6d.png)
![Screen Shot 2021-08-11 at 5 44 03 PM](https://user-images.githubusercontent.com/978440/129121789-77ab9a0d-fb82-4afa-aa0c-ef03e41912cc.png)
![casters-depth](https://user-images.githubusercontent.com/978440/129121791-02ef422f-be68-4ce0-9671-303817958721.jpeg)

**Comment by zackwoodruff** [comment]
![pointed-up](https://user-images.githubusercontent.com/8184416/129816120-9356a727-6090-4bc7-91ff-05bbf4c025fc.png)
![obstacle-avoidance-stream](https://user-images.githubusercontent.com/8184416/129816123-bed05c39-a13d-40cd-a686-5a0a7a0fb7d1.png)
![real-sense-camera-ui](https://user-images.githubusercontent.com/8184416/129816125-dbc6cd9a-b821-4e54-916a-439cbaa940f3.png)
![good-obstacle-view](https://user-images.githubusercontent.com/8184416/129816126-e709aece-477f-4cef-bbf0-88eaafbfa719.png)
![pitch-adjustment](https://user-images.githubusercontent.com/8184416/129816129-bf730c16-655f-43ea-95b7-e06393285db5.png)
![pointed-down](https://user-images.githubusercontent.com/8184416/129816130-5523b5f4-9210-4923-8583-53d8e02eeb56.png)

**Comment by georgechrysanthakopoulos** [comment]
[DM Camera Mount Upgrade (3767).pdf](https://github.com/directedmachines/customer-support/files/7038853/DM.Camera.Mount.Upgrade.3767.pdf)
[DM E-Stop Upgrade.pdf](https://github.com/directedmachines/customer-support/files/7038854/DM.E-Stop.Upgrade.pdf)
[Seesaw Caster Sliding Repair.pdf](https://github.com/directedmachines/customer-support/files/7038855/Seesaw.Caster.Sliding.Repair.pdf)

**Comment by georgechrysanthakopoulos** [comment]
![Screen Shot 2021-08-27 at 5 34 46 PM](https://user-images.githubusercontent.com/978440/131235793-6414614d-45ba-426e-907d-dca7b4e50ed9.png)
![Screen Shot 2021-08-27 at 5 36 49 PM](https://user-images.githubusercontent.com/978440/131235800-b7df45aa-f4cd-4c8d-83cb-581ec284ab40.png)
![thumbnail_image0](https://user-images.githubusercontent.com/978440/131235801-71da4356-6313-4c0f-bdee-289d6587d6ba.jpeg)

**Comment by georgechrysanthakopoulos** [comment]
[DM-HighCurrentPowerCycle.pdf](https://github.com/directedmachines/customer-support/files/7110656/DM-HighCurrentPowerCycle.pdf)

**Comment by georgechrysanthakopoulos** [comment]
[DM-HighCurrentPowerCycle.pdf](https://github.com/directedmachines/customer-support/files/7110722/DM-HighCurrentPowerCycle.pdf)

**Comment by georgechrysanthakopoulos** [comment]
<img width="552" alt="Screen Shot 2021-09-05 at 2 24 36 PM" src="https://user-images.githubusercontent.com/978440/132141836-f202bddf-3476-4ab5-af96-9d92948ac30d.png">

**Comment by georgechrysanthakopoulos** [comment]
![Image from iOS](https://user-images.githubusercontent.com/978440/134783239-530404e8-4cbb-444a-8c75-6fb12324e62f.jpg)

**Comment by georgechrysanthakopoulos** [comment]
<img width="648" alt="Screen Shot 2021-11-20 at 3 28 17 PM" src="https://user-images.githubusercontent.com/978440/142740106-573f8282-47ff-40b2-a9d4-9e0edefe011f.png">
<img width="462" alt="Screen Shot 2021-11-20 at 3 27 26 PM" src="https://user-images.githubusercontent.com/978440/142740110-3e2629e8-9d85-425c-8790-f0a729643dc5.png">
<img width="831" alt="Screen Shot 2021-11-20 at 3 26 40 PM" src="https://user-images.githubusercontent.com/978440/142740111-afe106a7-6931-43cb-bf00-0c47e60c882e.png">

**Comment by georgechrysanthakopoulos** [comment]
<img width="498" alt="Screen Shot 2021-11-20 at 4 28 29 PM" src="https://user-images.githubusercontent.com/978440/142741429-1cc37195-93e0-4d0f-a456-d80fe975c98e.png">

**Comment by georgechrysanthakopoulos** [comment]
<img width="1443" alt="Screen Shot 2021-11-14 at 9 10 34 AM" src="https://user-images.githubusercontent.com/978440/142742415-8fab1d39-3df8-4192-92f2-c4dafdbeddf5.png">

**Comment by georgechrysanthakopoulos** [comment]
![Screen Shot 2021-11-29 at 2 29 45 PM](https://user-images.githubusercontent.com/978440/143953551-00eccae4-b8a2-4d6a-bb89-ef15b812b76c.png)
![Screen Shot 2021-11-29 at 2 27 32 PM](https://user-images.githubusercontent.com/978440/143953553-886d5729-7209-415e-a1b6-7caf900dac38.png)

**Comment by georgechrysanthakopoulos** [comment]
![Screen Shot 2021-12-09 at 9 40 30 AM](https://user-images.githubusercontent.com/978440/145447787-809ee059-9502-44c3-a55e-ef4c9300b518.png)

**Comment by georgechrysanthakopoulos** [comment]
![Full LCR + Camera FOV Side View](https://user-images.githubusercontent.com/978440/152604144-b126f837-c730-4bdb-9eab-141440257f30.PNG)
![Full LCR + Camera FOV Aerial View](https://user-images.githubusercontent.com/978440/152604150-c36bcd46-ab91-46d2-927b-d80bde0e807b.PNG)

**Comment by georgechrysanthakopoulos** [comment]
![Screen Shot 2022-02-04 at 1 20 55 PM](https://user-images.githubusercontent.com/978440/152604704-1e30db69-e076-4654-b1d8-3428e3a7816f.png)

**Comment by georgechrysanthakopoulos** [comment]
![IMG_6260](https://user-images.githubusercontent.com/978440/152605036-2194374e-705d-4659-b98a-be38e144f833.jpg)

**Comment by georgechrysanthakopoulos** [comment]
![LCR With Labels](https://user-images.githubusercontent.com/978440/152610324-fc11c0f2-9686-4de8-a48c-120645c536b3.PNG)

**Comment by georgechrysanthakopoulos** [comment]
![Screen Shot 2022-03-30 at 6 15 14 PM](https://user-images.githubusercontent.com/978440/160957250-5d33d1fe-b72c-4d12-9f45-d6a9bfefda2e.png)

**Comment by georgechrysanthakopoulos** [comment]
![Screen Shot 2022-04-27 at 11 34 02 AM](https://user-images.githubusercontent.com/978440/165595973-f37666c5-df0e-4389-a5bf-edbab85ea65e.png)

**Comment by georgechrysanthakopoulos** [comment]
![Screen Shot 2022-04-27 at 11 36 35 AM](https://user-images.githubusercontent.com/978440/165596161-fcb16064-f0bc-4df3-bfda-fb1fdea69ff9.png)
