### ISSUE TITLE
UI Menu buttons overlapped 

### ISSUE THREAD

**Issue by robschneider16** [directedmachines/customer-support#7]
<img width="1680" alt="Screen Shot 2021-02-22 at 11 02 18 AM" src="https://user-images.githubusercontent.com/5422319/108756503-71d0f680-74fd-11eb-8fe2-aac406f61a81.png">

top left corner, Plan selection is shadowed by the configure button.

**Comment by robschneider16** [comment]
on a mac using google chrome fyi

**Comment by georgechrysanthakopoulos** [comment]
Will fix!

**Comment by georgechrysanthakopoulos** [comment]
<img width="730" alt="Screen Shot 2021-03-05 at 10 23 14 PM" src="https://user-images.githubusercontent.com/978440/110197594-6cc74d80-7e01-11eb-9650-2b899be304fb.png">
fixed
