### ISSUE TITLE
'New Path' not drawing green line if mouse hovered over robot motion path

### ISSUE THREAD

**Issue by robschneider16** [directedmachines/customer-support#8]
<img width="1680" alt="Screen Shot 2021-02-22 at 11 08 57 AM" src="https://user-images.githubusercontent.com/5422319/108757244-6e8a3a80-74fe-11eb-9aa7-788e2916f74c.png">

screenshot shows the green line when moving the mouse to create a new waypoint+path, then line stops updating/following cursor when the cursor is hovered over motion path 

When you move the mouse over a robot motion path, the updating of the green line will haunt (but if you click, it still places waypoint correctly)

so not critical, still works and not sure if its by design.

**Comment by robschneider16** [comment]
unfortunate that the cursor does not show up in the screenshots. but the first image, the cursor is at the end of the yellow LCR motion path on that same row

**Comment by georgechrysanthakopoulos** [comment]
thanks, will attempt fix, non trivial due to the weird behavior with Google Map V3 JS api and polylines.

**Comment by georgechrysanthakopoulos** [comment]
reproduced and fixed
